create table "public"."new_tabl" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "st_name" text
);


alter table "public"."new_tabl" enable row level security;

CREATE UNIQUE INDEX new_tabl_pkey ON public.new_tabl USING btree (id);

alter table "public"."new_tabl" add constraint "new_tabl_pkey" PRIMARY KEY using index "new_tabl_pkey";

grant delete on table "public"."new_tabl" to "anon";

grant insert on table "public"."new_tabl" to "anon";

grant references on table "public"."new_tabl" to "anon";

grant select on table "public"."new_tabl" to "anon";

grant trigger on table "public"."new_tabl" to "anon";

grant truncate on table "public"."new_tabl" to "anon";

grant update on table "public"."new_tabl" to "anon";

grant delete on table "public"."new_tabl" to "authenticated";

grant insert on table "public"."new_tabl" to "authenticated";

grant references on table "public"."new_tabl" to "authenticated";

grant select on table "public"."new_tabl" to "authenticated";

grant trigger on table "public"."new_tabl" to "authenticated";

grant truncate on table "public"."new_tabl" to "authenticated";

grant update on table "public"."new_tabl" to "authenticated";

grant delete on table "public"."new_tabl" to "service_role";

grant insert on table "public"."new_tabl" to "service_role";

grant references on table "public"."new_tabl" to "service_role";

grant select on table "public"."new_tabl" to "service_role";

grant trigger on table "public"."new_tabl" to "service_role";

grant truncate on table "public"."new_tabl" to "service_role";

grant update on table "public"."new_tabl" to "service_role";


